import { chromium } from 'playwright-core';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const page = await ctx.newPage();
await page.goto('http://localhost:5199/'); await page.evaluate(() => localStorage.clear()); await page.goto('http://localhost:5199/'); await page.reload();
const dump = async (label, sel = 'body') => { console.log(`\n===== ${label}`); console.log(await page.locator(sel).ariaSnapshot()); };
await page.getByRole('button', { name: 'Get started' }).waitFor();
await dump('SPLASH', 'body');
await page.getByRole('button', { name: 'Get started' }).click(); await page.getByRole('heading', { name: 'Set up your dashboard' }).waitFor(); await page.waitForTimeout(5000);
await dump('SETUP', 'body');
await page.getByRole('checkbox').click(); await page.getByRole('button', { name: 'Open dashboard' }).click();
await page.getByRole('button', { name: 'Dismiss tip' }).click();
await page.getByRole('button', { name: /^Day 4/ }).click(); await page.waitForTimeout(6000);
await dump('DASHBOARD, day 4 (banner, nav, main)', 'body');
await browser.close();
